[package]
name = "sandbox-workspace-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
sandbox-workspace = { path = ".." }
tempfile = "3"

[[bin]]
name = "workspace_fs"
path = "fuzz_targets/workspace_fs.rs"
test = false
doc = false
bench = false
