#!/usr/bin/env bash
set -euo pipefail
SRC="${1:-.}"
DEST="${2:-.}"
mkdir -p "$DEST/docs/p22" "$DEST/prompts/p22/phases" "$DEST/prompts/p22/phase_injections" "$DEST/scripts" "$DEST/tasks/p22"
cp -r "$SRC/docs/"* "$DEST/docs/p22/"
cp "$SRC/prompts/P22_CODEX_RUN_PROMPT.md" "$DEST/prompts/p22/P22_CODEX_RUN_PROMPT.md"
cp -r "$SRC/prompts/phases/"* "$DEST/prompts/p22/phases/"
cp -r "$SRC/phase_injections/"* "$DEST/prompts/p22/phase_injections/"
cp -r "$SRC/scripts/"* "$DEST/scripts/"
cp -r "$SRC/tasks/"* "$DEST/tasks/p22/"
cp "$SRC/AGENTS_P22.md" "$DEST/AGENTS_P22.md"
cp "$SRC/RUN_ORDER.md" "$DEST/P22_RUN_ORDER.md"
echo "Installed P22 Codex bundle into $DEST"
echo "Start Codex with: prompts/p22/P22_CODEX_RUN_PROMPT.md"
