//! Canonical monitored activity record — the unit of captured LLM activity.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use stack_ids::TraceCtx;

/// A single captured activity event from the stack.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonitoredEvent {
    /// Unique row ID (auto-generated by SQLite).
    #[serde(skip_serializing)]
    pub id: Option<i64>,

    /// When this event was captured (UTC).
    pub timestamp: DateTime<Utc>,

    /// Which stack crate emitted this activity.
    /// E.g. "llm-pipeline", "agent-graph-mcp", "semantic-memory".
    pub crate_name: String,

    /// What kind of activity this represents.
    /// Free-form but should follow conventions:
    /// - "llm_call" — an LLM API call (prompt → response)
    /// - "tool_invocation" — a tool/function call during an LLM loop
    /// - "tool_result" — the result of a tool invocation
    /// - "retry" — a retry attempt (semantic or transport)
    /// - "parse" — output parsing activity
    /// - "trace" — a tracing span/event snapshot
    /// - "embedding" — embedding generation
    /// - "graph_node" — agent-graph node execution
    /// - "info" / "warn" / "error" — log-level events
    pub event_type: String,

    /// Human-readable summary of what happened.
    /// E.g. " llama3.2:3b respond to 'Analyze this code' "
    pub summary: String,

    /// Optional structured detail (JSON).
    /// For llm_call: { "prompt": "...", "response": "...", "model": "...", "tokens": {...} }
    /// For tool_invocation: { "tool_name": "...", "args": "...", "result": "..." }
    /// For retry: { "attempt": 2, "reason": "...", "policy": "..." }
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,

    /// Trace context for cross-crate correlation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trace_ctx: Option<TraceCtx>,

    /// Optional attempt/trial IDs from stack-ids.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempt_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trial_id: Option<String>,

    /// Optional tags for filtering.
    /// E.g. ["streaming", "json_mode", "tool_loop", "graph_execution"]
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,

    /// Optional source span/file for debugging.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_loc: Option<String>,
}

impl MonitoredEvent {
    /// Create a new event with minimal fields.
    pub fn new(
        crate_name: impl Into<String>,
        event_type: impl Into<String>,
        summary: impl Into<String>,
    ) -> Self {
        Self {
            id: None,
            timestamp: Utc::now(),
            crate_name: crate_name.into(),
            event_type: event_type.into(),
            summary: summary.into(),
            detail: None,
            trace_ctx: None,
            attempt_id: None,
            trial_id: None,
            tags: Vec::new(),
            source_loc: None,
        }
    }

    /// Attach trace context.
    pub fn with_trace(mut self, trace_ctx: TraceCtx) -> Self {
        self.trace_ctx = Some(trace_ctx);
        self
    }

    /// Attach trace context (if present).
    pub fn with_trace_opt(mut self, trace_ctx: Option<TraceCtx>) -> Self {
        if let Some(tc) = trace_ctx {
            self.trace_ctx = Some(tc);
        }
        self
    }

    /// Attach an attempt ID (if present).
    pub fn with_attempt_opt(mut self, attempt_id: Option<impl Into<String>>) -> Self {
        if let Some(a) = attempt_id {
            self.attempt_id = Some(a.into());
        }
        self
    }

    /// Attach a trial ID (if present).
    pub fn with_trial_opt(mut self, trial_id: Option<impl Into<String>>) -> Self {
        if let Some(t) = trial_id {
            self.trial_id = Some(t.into());
        }
        self
    }

    /// Attach an attempt ID.
    pub fn with_attempt(mut self, attempt_id: impl Into<String>) -> Self {
        self.attempt_id = Some(attempt_id.into());
        self
    }

    /// Attach a trial ID.
    pub fn with_trial(mut self, trial_id: impl Into<String>) -> Self {
        self.trial_id = Some(trial_id.into());
        self
    }

    /// Add a tag.
    pub fn with_tag(mut self, tag: impl Into<String>) -> Self {
        self.tags.push(tag.into());
        self
    }

    /// Set structured detail (JSON string).
    pub fn with_detail(mut self, detail: impl Into<String>) -> Self {
        self.detail = Some(detail.into());
        self
    }

    /// Set the source location (file:line).
    pub fn with_source(mut self, source: impl Into<String>) -> Self {
        self.source_loc = Some(source.into());
        self
    }

    /// Convenience: build an LLM call event.
    pub fn llm_call(
        crate_name: impl Into<String>,
        model: impl Into<String>,
        prompt_preview: impl Into<String>,
        trace_ctx: Option<TraceCtx>,
        attempt_id: Option<String>,
    ) -> Self {
        Self::new(
            crate_name,
            "llm_call",
            format!("→ {} : {}", model.into(), prompt_preview.into()),
        )
        .with_trace_opt(trace_ctx)
        .with_attempt_opt(attempt_id)
        .with_tag("llm")
    }

    /// Convenience: build a tool invocation event.
    pub fn tool_invocation(
        crate_name: impl Into<String>,
        tool_name: impl Into<String>,
        trace_ctx: Option<TraceCtx>,
    ) -> Self {
        Self::new(
            crate_name,
            "tool_invocation",
            format!("🔧 call {}", tool_name.into()),
        )
        .with_trace_opt(trace_ctx)
        .with_tag("tool")
    }
}

/// Query filter for activity search.
#[derive(Debug, Clone, Default)]
pub struct ActivityFilter {
    /// Optional crate name filter.
    pub crate_name: Option<String>,
    /// Optional event type filter.
    pub event_type: Option<String>,
    /// Optional trace ID filter (matches partial or full).
    pub trace_id: Option<String>,
    /// Optional tag filter (event must have ALL specified tags).
    pub tags: Vec<String>,
    /// Time range (inclusive lower bound).
    pub after: Option<DateTime<Utc>>,
    /// Time range (inclusive upper bound).
    pub before: Option<DateTime<Utc>>,
    /// Maximum results to return.
    pub limit: Option<usize>,
    /// Offset for pagination.
    pub offset: Option<usize>,
}

/// Aggregated stats for a time window.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityStats {
    /// Total events captured.
    pub total_events: u64,
    /// Events by type.
    pub by_type: Vec<(String, u64)>,
    /// Events by crate.
    pub by_crate: Vec<(String, u64)>,
    /// Total LLM calls.
    pub llm_calls: u64,
    /// Total tool invocations.
    pub tool_invocations: u64,
    /// Time window (for display).
    pub window_start: DateTime<Utc>,
    pub window_end: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn convenience_constructors_preserve_absent_lineage() {
        let llm = MonitoredEvent::llm_call("llm-pipeline", "model", "preview", None, None);
        assert!(llm.trace_ctx.is_none());
        assert!(llm.attempt_id.is_none());

        let tool = MonitoredEvent::tool_invocation("llm-tool-runtime", "search", None);
        assert!(tool.trace_ctx.is_none());
    }
}
