#!/usr/bin/env python3
from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from release_gate_set import RELEASE_GATE_COMMANDS, gate_sha256


ROOT = Path(__file__).resolve().parent.parent
EVIDENCE_MANIFEST = ROOT / "STATUS_EVIDENCE_MANIFEST.json"
RECEIPT_GENERATOR = "python3 scripts/generate_closeout_receipt.py"
RECEIPT_CHECK = "python3 scripts/check_closeout_receipt.py"
ARTIFACT_FILES = [
    "STATUS_DASHBOARD.md",
    "SUPPORT_PROFILE.md",
    "scripts/release_gate_set.py",
    "scripts/check_no_prod_panics.sh",
    "scripts/public_type_drift_allowlist.json",
    "docs/archive/root_closeout_history/manifest.json",
    "release/closeout_receipt_v1.json",
]


def build_manifest(results: list[dict[str, str]], captured_at: datetime) -> dict[str, object]:
    return {
        "snapshot": f"{captured_at.date().isoformat()}-hardening-closeout",
        "captured_at": captured_at.date().isoformat(),
        "captured_at_local": captured_at.isoformat(timespec="seconds"),
        "gate_definition": {
            "path": "scripts/release_gate_set.py",
            "sha256": gate_sha256(),
            "command_count": len(RELEASE_GATE_COMMANDS),
        },
        "proof_commands": RELEASE_GATE_COMMANDS,
        "proof_results": results,
        "artifact_files": ARTIFACT_FILES,
        "notes": [
            "This ledger is generated by scripts/run_release_gates.py from the canonical gate list in scripts/release_gate_set.py.",
            "make gate reruns the same commands in the same order and rewrites this ledger before regenerating the closeout receipt.",
            "The receipt is a derivative artifact. It must not be treated as independent proof of gate success.",
        ],
    }


def run_command(command: str) -> int:
    print(f"+ {command}", flush=True)
    completed = subprocess.run(command, shell=True, cwd=ROOT)
    return completed.returncode


def write_manifest(results: list[dict[str, str]], captured_at: datetime) -> None:
    manifest = build_manifest(results, captured_at)
    EVIDENCE_MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    captured_at = datetime.now().astimezone()
    results: list[dict[str, str]] = []

    for command in RELEASE_GATE_COMMANDS:
        exit_code = run_command(command)
        result = "pass" if exit_code == 0 else "fail"
        results.append({"command": command, "result": result})
        if exit_code != 0:
            write_manifest(results, captured_at)
            print(f"release gate failed at: {command}", file=sys.stderr)
            return exit_code

    write_manifest(results, captured_at)

    for command in (RECEIPT_GENERATOR, RECEIPT_CHECK):
        exit_code = run_command(command)
        if exit_code != 0:
            print(f"release publication step failed at: {command}", file=sys.stderr)
            return exit_code

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
