def validate_shape_json(shape_json: str) -> str: ...
def build_synthetic_pool_receipts_json(shape_json: str) -> str: ...
def attach_synthetic_reader_receipt_json(shape_json: str) -> str: ...
def decode_synthetic_slice_receipt_json(
    shape_json: str,
    role: str,
    layer: int,
    start: int,
    end: int,
) -> str: ...
def build_pool_from_f32_json(shape_json: str, blocks_json: str) -> str: ...
